### ISSUE TITLE
Autocreate user

### ISSUE THREAD

**Issue by psy** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#1]
If you want the extension to autocreate users not existing you have to add 

```
$wgGroupPermissions['*']['autocreateaccount']   = true;
```

to your LocalSettings.php

**Comment by fnk** [comment]
Thanks psy.
I added that to the README.md

Furthermore, our code is currently being integrated in the official Extension:
  https://phabricator.wikimedia.org/T110292
  https://gerrit.wikimedia.org/r/#/c/308683/

I hope this gets released soon so that we cann pull from there or close this repo.
In the meantime you might want to follow the progress over at mediawiki.org.

Cheers,
Andi.
